#!/bin/sh -e

# Validate the commit message.

MAX_LENGTH=60
fatal() { printf '\033[31mERROR: %s\033[0m\n' "$*" ; exit 1 ; }


# Length. GitHub summaries fit 60 characters.
echo "Checking message length"
len=$(awk '{print length($0); exit} ' "$1")
if [ -z "$len" ]; then
    fatal "message is empty"
elif [ "$len" -gt "$MAX_LENGTH" ]; then
    fatal "message length is $len but should not exceed $MAX_LENGTH"
fi


echo "Checking space characters"
if awk '/(^ )|(  )|( [,!?])/ {exit 0} {exit 1}' "$1"; then
    fatal "misplaced space characters in message"
fi


# Sentence.
echo "Checking sentential validity"
if awk '/^[A-Z].*[.?!]$/ {exit 1} {exit 0}' "$1"; then
    fatal "message does not start with [A-Z] and end in [.?!]"
fi


# Spelling.
echo "Checking message spelling"
typos "$1"
