#!/bin/sh -e

# Run the spell checker, linter, and unit tests on every commit. The working
# directory of this script will be the top level of the Git repository.


# Temporary storage. Single quotes on `$d` to expand now, not when signalled.
d=$(mktemp -d "/tmp/$(basename "$0").XXXXXX")
# shellcheck disable=SC2064
trap "rm -rf -- '$d'" EXIT
trap exit INT TERM


# Identify relevant files. BusyBox's `awk` cannot print null characters.
list() { git diff -z --staged --name-only --diff-filter=ACMRT -- "$@" ; }
staged="$d/staged"
python="$d/python"
markdown="$d/md"
yaml="$d/yaml"
shell="$d/shell"
list                     >"$staged"
list '*.py'              >"$python"
list '*.md' '*.markdown' >"$markdown"
list '*.yaml' '*.yml'    >"$yaml"
xargs -0r file -i <"$staged" |
    awk -F: '/x-shellscript/ { print $1 }' |
        tr '\n' '\0' >"$shell"


# Copy the staged tree. In case of a partial commit, we want to run tests on
# the staged files, not the working tree.
git checkout-index --prefix="$d/" -a
cd "$d"


if [ -s "$staged" ]; then
    echo "Running spell checker"
    xargs -0 typos <"$staged"
fi

if [ -s "$python" ]; then
    echo "Running Python linter"
    xargs -0 ruff check -q <"$python"
fi

if [ -s "$shell" ]; then
    echo "Running shell linter"
    xargs -0 shellcheck <"$shell"
fi

if [ -s "$markdown" ]; then
    echo "Running Markdown linter"
    xargs -0 pymarkdown scan <"$markdown"
fi

if [ -s "$yaml" ]; then
    echo "Running YAML linter"
    xargs -0 yamllint -s <"$yaml"
fi

echo "Running unit tests"
pytest -q tests/unit
